vscode:
  extensions:
    - ms-python.python

tasks:
  - init: sudo add-apt-repository -y ppa:deadsnakes/ppa && sudo apt install -y python3.6 python3.7 python3.8 python3.9
    command: pip3 install numpy
