before_script:
  - python -V
  - pip install numpy

stages:
  - test
  - merge

.tests:
  script:
  - python -m unittest discover tests

testpython35:
  extends: .tests
  image: python:3.5

testpython36:
  extends: .tests
  image: python:3.6
  
testpython37:
  extends: .tests
  image: python:3.7
