before_script:
  - python -V
  - pip install numpy

stages:
  - test
  - build
  - publish

.tests:
  script:
  - python -m unittest discover tests

testpython35:
  extends: .tests
  image: python:3.5

testpython36:
  extends: .tests
  image: python:3.6

testpython37:
  extends: .tests
  image: python:3.7

pack:
  image: python:3.6
  stage: build
  only:
    - master@szuro/pylarization
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1h
    paths:
      - dist/

publish:
  image: python:3.6
  stage: publish
  only:
    - master@szuro/pylarization
  script:
    - pip install twine
    - python -m twine upload dist/*